### ISSUE TITLE
bingus

### ISSUE THREAD

**Issue by EvanLin1729** [CSF2223/mygallery-Brian-OConnell#2]
bingus

**Comment by EvanLin1729** [comment]
![Screenshot 2022-06-07 11 31 40 AM](https://user-images.githubusercontent.com/70862234/191604513-3cfaf58d-4475-4514-8011-4d97dd270ce8.png)

**Comment by AudreyFencil** [comment]
![hulkLin](https://user-images.githubusercontent.com/70925008/191604527-8dc134fd-45d6-487b-ad7d-b70f583fce30.jpg)

**Comment by EvanLin1729** [comment]
![picture-e638548609da237b9beb9fb6bd7179ac_618ec479e0264](https://user-images.githubusercontent.com/70862234/191604595-7d12ab66-b87a-4948-89ab-f20ad7533fbb.jpg)

**Comment by EvanLin1729** [comment]
![Screenshot 2022-05-17 11 35 36 AM](https://user-images.githubusercontent.com/70862234/191604641-416b89e3-1ed8-4217-a60a-2dee9af7f811.png)

**Comment by AudreyFencil** [comment]
![sleepyLin](https://user-images.githubusercontent.com/70925008/191604684-ff3b1084-fb6b-4368-a086-12fda8c4cfe4.jpg)

**Comment by EvanLin1729** [comment]
![Uploading laughing-ben-shapiro.gif…]()

**Comment by AudreyFencil** [comment]
![avatars-lQlek4KafT0IHJvz-ovjKTw-t500x500](https://user-images.githubusercontent.com/70925008/191604908-45ade990-592c-473b-ab2f-822fb925a708.jpg)

**Comment by EvanLin1729** [comment]
[Milgram Study Obey at Any Cost.pdf](https://github.com/CSF2223/mygallery-Brian-OConnell/files/9620183/Milgram.Study.Obey.at.Any.Cost.pdf)

**Comment by AudreyFencil** [comment]
![crazyLin](https://user-images.githubusercontent.com/70925008/191605075-eeb1c939-8aae-4c1a-8f15-a5e06651d11d.jpg)

**Comment by EvanLin1729** [comment]
![Screenshot 2022-09-21 4 35 11 PM](https://user-images.githubusercontent.com/70862234/191605177-155acf9a-6cfe-4d9d-8f1e-597a47e887c2.png)

**Comment by AudreyFencil** [comment]
![zdSsqm_L_400x400](https://user-images.githubusercontent.com/70925008/191605190-97b89b67-6f8f-4814-b172-2383ad76a959.jpg)

**Comment by AudreyFencil** [comment]
![Uploading ur-mom-run.gif…]()

**Comment by AudreyFencil** [comment]
![ur-mom-run](https://user-images.githubusercontent.com/70925008/191605355-cc0e68bb-5367-462f-bafd-ad6d0bc74dac.gif)

**Comment by EvanLin1729** [comment]
![dsafdasfsgsgds](https://user-images.githubusercontent.com/70862234/191605536-de70bba3-c9c3-4526-bac7-10b875f36783.png)

**Comment by AudreyFencil** [comment]
![ur-mom-get](https://user-images.githubusercontent.com/70925008/191605579-30e32814-7ea9-410f-9797-ecc4bc06b9e0.jpg)

**Comment by EvanLin1729** [comment]
![dskahfkjdsafhkjdsdsf](https://user-images.githubusercontent.com/70862234/191605616-ade9f1a2-b2ef-40e1-ab47-4bcb17424f9a.png)

**Comment by AudreyFencil** [comment]
![image](https://user-images.githubusercontent.com/70925008/191605861-7c012b2e-40e8-4150-9221-9ecc26f93dbb.png)

**Comment by EvanLin1729** [comment]
@Brian-OConnell u haves sily

**Comment by EvanLin1729** [comment]
@Brian-OConnell u haves sily

**Comment by AudreyFencil** [comment]
![Uploading dd2358l-56806230-d93c-4176-a5c6-d2d3eddbe9f5.png…]()

**Comment by AudreyFencil** [comment]
![dd2358l-56806230-d93c-4176-a5c6-d2d3eddbe9f5](https://user-images.githubusercontent.com/70925008/191606244-5a7f097e-c5e0-4b46-8e16-2ddcb3128eb6.png)

**Comment by AudreyFencil** [comment]
![mr-incredible](https://user-images.githubusercontent.com/70925008/191638991-ae7d5c5c-49e5-4ab2-83e4-cc44eb29d5b7.jpg)

**Comment by EvanLin1729** [comment]
<h1 id="firstHeading" class="firstHeading" lang="en" style="color: rgb(0, 0, 0); margin: 0px 0px 0.25em; padding: 0px; overflow: visible; border-bottom: 1px solid rgb(162, 169, 177); font-size: 1.8em; font-weight: normal; font-family: &quot;Linux Libertine&quot;, Georgia, Times, serif; line-height: 1.3; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Jacob Hardin-Bernhardt</h1><div id="bodyContent" class="mw-body-content" style="position: relative; z-index: 0; font-size: calc(0.875em); line-height: 1.6; color: rgb(32, 33, 34); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div id="contentSub" style="font-size: 11.76px; line-height: 1.2em; margin: 0px 0px 1.4em 1em; color: rgb(84, 89, 93); width: auto;"></div><div id="contentSub2" style="font-size: 11.76px; line-height: 1.2em; margin: 0px 0px 1.4em 1em; color: rgb(84, 89, 93); width: auto;"></div><div id="jump-to-nav"></div><a class="mw-jump-link" href="https://www.qbwiki.com/wiki/Jacob_Hardin-Bernhardt#mw-head" style="text-decoration: none; color: rgb(6, 69, 173); background: none; display: block; clip: rect(1px, 1px, 1px, 1px); width: 1px; height: 1px; margin: -1px; border: 0px; padding: 0px; overflow: hidden; position: absolute !important;">Jump to navigation</a><a class="mw-jump-link" href="https://www.qbwiki.com/wiki/Jacob_Hardin-Bernhardt#searchInput" style="text-decoration: none; color: rgb(6, 69, 173); background: none; display: block; clip: rect(1px, 1px, 1px, 1px); width: 1px; height: 1px; margin: -1px; border: 0px; padding: 0px; overflow: hidden; position: absolute !important;">Jump to search</a><div id="mw-content-text" lang="en" dir="ltr" class="mw-content-ltr" style="direction: ltr;"><div class="mw-parser-output">

Jacob Hardin-Bernhardt
--
Noted subjects | History, CE
Current college | none
Past colleges | none
High school | Hunter (2019-present)
Middle school | Hunter (2017-2019)
Stats | HDWhite • NAQT

<p style="margin: 0.5em 0px;"><b>Jacob Hardin-Bernhardt</b><span> </span>is a member of the class of 2023 and a history/current events-based generalist at<span> </span><a href="https://www.qbwiki.com/wiki/Hunter_College_High_School" class="mw-redirect" title="Hunter College High School" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">Hunter College High School</a><span> </span>in New York, New York.</p><h2 style="color: rgb(0, 0, 0); margin: 1em 0px 0.25em; padding: 0px; overflow: hidden; border-bottom: 1px solid rgb(162, 169, 177); font-size: 1.5em; font-weight: normal; font-family: &quot;Linux Libertine&quot;, Georgia, Times, serif; line-height: 1.3;"><span class="mw-headline" id="Notable_Achievements">Notable Achievements</span></h2><ul style="list-style-image: url(&quot;/w/skins/Vector/resources/skins.vector.styles/images/bullet-icon.svg?d4515&quot;); margin: 0.3em 0px 0px 1.6em; padding: 0px;"><li style="margin-bottom: 0.1em;">Member of the 8th place Hunter team at<span> </span><a href="https://www.qbwiki.com/wiki/2018_MSNCT" title="2018 MSNCT" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">2018 MSNCT</a></li><li style="margin-bottom: 0.1em;">Captain of the 1st place Hunter A team at<span> </span><a href="https://www.qbwiki.com/wiki/2019_MSNCT" title="2019 MSNCT" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">2019 MSNCT</a></li><li style="margin-bottom: 0.1em;">5th place individually at 2019 MS IPNCT</li><li style="margin-bottom: 0.1em;">Member of the 1st place Hunter A team at 2019 JV NHBB</li><li style="margin-bottom: 0.1em;">Member of the 4th place Hunter A team at 2019 JV NHBB</li><li style="margin-bottom: 0.1em;">Member of the 3rd place Hunter A team at 2019 JV NHBB</li><li style="margin-bottom: 0.1em;">Member of the 1st place Hunter A team at 2022 Varsity NHBB</li><li style="margin-bottom: 0.1em;">5th place individually at 2020 JV US History Bee</li><li style="margin-bottom: 0.1em;">2nd place individually at 2021 JV Political Science Bee</li><li style="margin-bottom: 0.1em;">4th place individually at 2022 Varsity History Bee</li><li style="margin-bottom: 0.1em;">Member of the 19th place Hunter B team at<span> </span><a href="https://www.qbwiki.com/wiki/2021_HSNCT" title="2021 HSNCT" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">2021 HSNCT</a></li></ul></div></div></div>Jacob Hardin-Bernhardt
[Jump to navigation](https://www.qbwiki.com/wiki/Jacob_Hardin-Bernhardt#mw-head)[Jump to search](https://www.qbwiki.com/wiki/Jacob_Hardin-Bernhardt#searchInput)
Jacob Hardin-Bernhardt
Noted subjects	History, CE
Current college	none
Past colleges	none
High school	[Hunter](https://www.qbwiki.com/wiki/Hunter) (2019-present)
Middle school	[Hunter](https://www.qbwiki.com/wiki/Hunter) (2017-2019)
Stats	[HDWhite](https://hdwhite.org/qb/stats/player/Jacob+Hardin-Bernhardt) • [NAQT](https://www.naqt.com/stats/player/search.jsp?PASSBACK=PLAYER_SEARCH&first_name=Jacob&last_name=Hardin-Bernhardt)
Jacob Hardin-Bernhardt is a member of the class of 2023 and a history/current events-based generalist at [Hunter College High School](https://www.qbwiki.com/wiki/Hunter_College_High_School) in New York, New York.

Notable Achievements
Member of the 8th place Hunter team at [2018 MSNCT](https://www.qbwiki.com/wiki/2018_MSNCT)
Captain of the 1st place Hunter A team at [2019 MSNCT](https://www.qbwiki.com/wiki/2019_MSNCT)
5th place individually at 2019 MS IPNCT
Member of the 1st place Hunter A team at 2019 JV NHBB
Member of the 4th place Hunter A team at 2019 JV NHBB
Member of the 3rd place Hunter A team at 2019 JV NHBB
Member of the 1st place Hunter A team at 2022 Varsity NHBB
5th place individually at 2020 JV US History Bee
2nd place individually at 2021 JV Political Science Bee
4th place individually at 2022 Varsity History Bee
Member of the 19th place Hunter B team at [2021 HSNCT](https://www.qbwiki.com/wiki/2021_HSNCT)

**Comment by EvanLin1729** [comment]
<h1 id="firstHeading" class="firstHeading" lang="en" style="color: rgb(0, 0, 0); margin: 0px 0px 0.25em; padding: 0px; overflow: visible; border-bottom: 1px solid rgb(162, 169, 177); font-size: 1.8em; font-weight: normal; font-family: &quot;Linux Libertine&quot;, Georgia, Times, serif; line-height: 1.3; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Arthur Gayden</h1><div id="bodyContent" class="mw-body-content" style="position: relative; z-index: 0; font-size: calc(0.875em); line-height: 1.6; color: rgb(32, 33, 34); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div id="contentSub" style="font-size: 11.76px; line-height: 1.2em; margin: 0px 0px 1.4em 1em; color: rgb(84, 89, 93); width: auto;"></div><div id="contentSub2" style="font-size: 11.76px; line-height: 1.2em; margin: 0px 0px 1.4em 1em; color: rgb(84, 89, 93); width: auto;"></div><div id="jump-to-nav"></div><a class="mw-jump-link" href="https://www.qbwiki.com/wiki/Arthur_Gayden#mw-head" style="text-decoration: none; color: rgb(6, 69, 173); background: none; display: block; clip: rect(1px, 1px, 1px, 1px); width: 1px; height: 1px; margin: -1px; border: 0px; padding: 0px; overflow: hidden; position: absolute !important;">Jump to navigation</a><a class="mw-jump-link" href="https://www.qbwiki.com/wiki/Arthur_Gayden#searchInput" style="text-decoration: none; color: rgb(6, 69, 173); background: none; display: block; clip: rect(1px, 1px, 1px, 1px); width: 1px; height: 1px; margin: -1px; border: 0px; padding: 0px; overflow: hidden; position: absolute !important;">Jump to search</a><div id="mw-content-text" lang="en" dir="ltr" class="mw-content-ltr" style="direction: ltr;"><div class="mw-parser-output">

Arthur Gayden
--
Noted subjects | US History, Literature, Geography, Current Events
High school | Detroit Country Day (2019-)
Stats | HDWhite • NAQT

<p style="margin: 0.5em 0px;"><b>Arthur Gayden</b><span> </span>is the captain of<span> </span><a href="https://www.qbwiki.com/wiki/Detroit_Country_Day" title="Detroit Country Day" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">Detroit Country Day</a>'s quiz bowl team. He is a US-based generalist, meaning that he specializes in US history, US literature, etc. In 2021, Arthur became the head editor of<span> </span><a href="https://www.qbwiki.com/wiki/DART" title="DART" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">DART</a>, a high school hard level charity housewrite produced by the<span> </span><a href="https://www.qbwiki.com/wiki/Detroit_Country_Day" title="Detroit Country Day" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">Detroit Country Day</a><span> </span>Quiz Bowl team. Arthur is notably an avid defender of<span> </span><a href="https://www.qbwiki.com/wiki/NAQT_Invitational_Series" title="NAQT Invitational Series" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">NAQT Invitational Series</a><span> </span>sets, defending the quality of its questions under any circumstances.</p><p style="margin: 0.5em 0px;">Arthur led the all-sophomore DCDS B team to win the JV title at the 2021<span> </span><a href="https://www.qbwiki.com/wiki/PACE_NSC" class="mw-redirect" title="PACE NSC" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">PACE NSC</a>. The young DCDS team also finished 31st at their first HSNCT.</p></div></div></div>Arthur Gayden
[Jump to navigation](https://www.qbwiki.com/wiki/Arthur_Gayden#mw-head)[Jump to search](https://www.qbwiki.com/wiki/Arthur_Gayden#searchInput)
Arthur Gayden
Noted subjects	US History, Literature, Geography, Current Events
High school	[Detroit Country Day](https://www.qbwiki.com/wiki/Detroit_Country_Day) (2019-)
Stats	[HDWhite](https://hdwhite.org/qb/stats/player/Arthur+Gayden) • [NAQT](https://www.naqt.com/stats/player/search.jsp?PASSBACK=PLAYER_SEARCH&first_name=Arthur&last_name=Gayden)
Arthur Gayden is the captain of [Detroit Country Day](https://www.qbwiki.com/wiki/Detroit_Country_Day)'s quiz bowl team. He is a US-based generalist, meaning that he specializes in US history, US literature, etc. In 2021, Arthur became the head editor of [DART](https://www.qbwiki.com/wiki/DART), a high school hard level charity housewrite produced by the [Detroit Country Day](https://www.qbwiki.com/wiki/Detroit_Country_Day) Quiz Bowl team. Arthur is notably an avid defender of [NAQT Invitational Series](https://www.qbwiki.com/wiki/NAQT_Invitational_Series) sets, defending the quality of its questions under any circumstances.

Arthur led the all-sophomore DCDS B team to win the JV title at the 2021 [PACE NSC](https://www.qbwiki.com/wiki/PACE_NSC). The young DCDS team also finished 31st at their first HSNCT.

**Comment by EvanLin1729** [comment]
[https://www.youtube.com/watch?v=xvFZjo5PgG0](url)

**Comment by EvanLin1729** [comment]
https://www.youtube.com/watch?v=xvFZjo5PgG0

**Comment by AudreyFencil** [comment]
![cool-mom](https://user-images.githubusercontent.com/70925008/191640043-f85683c1-1d22-47e7-b364-22181a1b3487.gif)

**Comment by EvanLin1729** [comment]
https://www.youtube.com/watch?v=xvFZjo5PgG0
